name: p38
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.3.1
  - alsa-lib=1.2.6.1
  - altgraph=0.17.2
  - aom=3.3.0
  - attrs=21.4.0
  - blosc=1.21.1
  - boost-cpp=1.74.0
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.0
  - cfitsio=4.1.0
  - charset-normalizer=2.0.12
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cryptography=37.0.1
  - curl=7.83.1
  - cycler=0.11.0
  - dbus=1.13.6
  - draco=1.5.2
  - eigen=3.4.0
  - expat=2.4.8
  - ffmpeg=4.4.1
  - fiona=1.8.21
  - folium=0.12.1.post1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - fpdf=1.7.2
  - freeglut=3.2.2
  - freetype=2.10.4
  - freetype-py=2.3.0
  - freexl=1.0.6
  - gdal=3.4.3
  - geojson=2.5.0
  - geopandas=0.10.2
  - geopandas-base=0.10.2
  - geos=3.10.2
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - greenlet=1.1.2
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - harfbuzz=4.2.0
  - hdf4=4.2.15
  - hdf5=1.12.1
  - hsluv=5.0.2
  - icu=69.1
  - idna=3.3
  - iniconfig=1.1.1
  - jasper=2.0.33
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.16
  - kealib=1.4.15
  - keyutils=1.6.1
  - kiwisolver=1.4.3
  - krb5=1.19.3
  - lame=3.100
  - laspy=2.1.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=13.0.1
  - libcurl=7.83.1
  - libdap4=3.20.6
  - libdeflate=1.12
  - libdrm=2.4.111
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgdal=3.4.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.70.2
  - libglu=9.0.0
  - libgomp=12.1.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm13=13.0.1
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopencv=4.5.5
  - libopus=1.3.1
  - libpciaccess=0.16
  - libpng=1.6.37
  - libpq=14.2
  - libprotobuf=3.19.4
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libva=2.14.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - macholib=1.16
  - mapclassify=2.4.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - memory_profiler=0.60.0
  - munch=2.5.0
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - ncurses=6.3
  - nettle=3.6
  - networkx=2.8.4
  - nitro=2.7.dev6
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.0
  - opencv=4.5.5
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.4
  - packaging=21.3
  - pandas=1.4.3
  - pcre=8.45
  - pdal=2.4.1
  - pillow=9.1.1
  - pip=22.1.2
  - pixman=0.40.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - proj=9.0.0
  - psutil=5.9.1
  - pthread-stubs=0.4
  - py-opencv=4.5.5
  - pycparser=2.21
  - pyinstaller=5.1
  - pyinstaller-hooks-contrib=2022.7
  - pympler=0.9
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyproj=3.3.1
  - pyqt=5.12.3
  - pyshp=2.3.0
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python-pdal=3.1.2
  - python_abi=3.8
  - pytz=2022.1
  - qt=5.12.9
  - rasterio=1.2.10
  - readline=8.1.2
  - requests=2.28.0
  - rtree=1.0.0
  - scikit-learn=1.1.1
  - scipy=1.8.1
  - setuptools=62.6.0
  - shapely=1.8.2
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlalchemy=1.4.37
  - sqlite=3.38.5
  - svt-av1=0.9.1
  - threadpoolctl=3.1.0
  - tiledb=2.8.3
  - tk=8.6.12
  - tornado=6.1
  - tzcode=2022a
  - tzdata=2022a
  - unicodedata2=14.0.0
  - unidecode=1.3.4
  - urllib3=1.26.9
  - vispy=0.10.0
  - wheel=0.37.1
  - x264=1!161.3030
  - x265=3.5
  - xerces-c=3.2.3
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.6.0
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pdal-plugins==1.2.0
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - tksheet==5.3.9
